active_toplogy: box
mu_sq: -1e9
dual: true
# alpha: 1.0 # optional, defaults to sqrt(s)
multi_channeling: false
regions: false
param_mode: weinzierl_ext

# integration settings
min_eval: 10
nstart: 100000
nincrease: 5000
max_eval: 10000000
cores: 4
seed: 1 # use pseudo-random numbers
# Parameters controlling the survey+refine stragey
# Set refine_n_runs < 0 to disable it.
refine_n_runs : 20
refine_n_points : 10000000
survey_n_iterations : 5
survey_n_points : 10000000


# list of topologies
topologies:
    double-triangle:
        loops: 2
        e_cm_sq: 1.0
        external_momenta: 
            - [1.0, 0., 0., 0.]
        id: 1 # deformation ID
        name: ""
    triangle-box:
        loops: 2
        e_cm_sq: 1.0
        external_momenta:
            - [1.0, 0.0, 0.0, 0.0]
            - [-0.59375, -0.0, -0.0, -0.32021721143623744]
            - [-0.40625, -0.0, -0.0, 0.32021721143623744]
        id: 2
        name: ""
    triangle-box-alternative:
        loops: 2
        e_cm_sq: 1.0
        external_momenta:
            - [1.0, 0.0, 0.0, 0.0]
            - [-0.59375, -0.0, -0.0, -0.32021721143623744]
            - [-0.40625, -0.0, -0.0, 0.32021721143623744]
        id: 3
        name: ""
    box:
        loops: 1
        e_cm_sq: 0.947492
        name: box1L_direct_integration
        id: 0
        external_momenta: &box_ext
            - [-0.47809952420694085, 0, 0, -0.4675244967345596]
            - [-0.5085067895779792, 0, 0, 0.4675244967345596]
            - [0.45782801395958195, 0.13758384614384497, 0.0812175730388203, -0.3067260691172595]
            - [0.5287782998253381, -0.13758384614384497, -0.0812175730388203, 0.3067260691172595]
    double-box:
        loops: 2
        e_cm_sq: 0.947492
        name: ""
        id: 0
        external_momenta: *box_ext
    double-box-SB:
        # Analytical result quoted by SB (exactly real) : -1.43249e-7
        loops: 2
        e_cm_sq: 90.0
        name: ""
        id: 5
        external_momenta:
            - [19.6586, -7.15252, -0.206016, 8.96383]
            - [26.874, 7.04203, -0.0501295, -12.9055]
            - [43.4674, 0.11049, 0.2561455, 3.94167]
            - [-90.0, 0.0, 0.0, 0.0]        
    diagonal-box:
        loops: 2
        e_cm_sq: 0.947492
        name: ""
        id: 4
        external_momenta: *box_ext
