#!/bin/bash

# Compilers:                                                                                                                                              
UNAME_S=$(uname -s)
PWD=$(pwd)

case ${UNAME_S} in
    Linux*)
	SO_DEFORM=target/release/libdeformation.so
	SO_INTEGRATOR=target/release/libintegrator.so
	SO_INTEGRAND=target/release/libintegrand.so;;
    Darwin*)
	SO_DEFORM=target/release/libdeformation.dylib
	SO_INTEGRATOR=target/release/libintegrator.dylib
	SO_INTEGRAND=target/release/libintegrand.dylib;;
    *)
	echo "UNKNOWN:${UNAME_S}"
	exit 0
esac

#Build libraries for python 
cd rust_backend/
cargo build --release

#Rename them to be called from MadGraph
cp ${SO_DEFORM} deform.so
cp ${SO_INTEGRAND} integrand.so
cp ${SO_INTEGRATOR} integrator.so

