#!/bin/bash

# Compilers:                                                                                                                                              
UNAME_S=$(uname -s)
PWD=$(pwd)

if [ `grep -rin '#default = \[\"python_api\"\]' rust_backend/ltd/Cargo.toml | wc -l` -eq 1 ]
then
	echo 'Befoe running this script, you must uncomment the line:'
	echo '   #default = ["python_api"]'
	echo 'in rust_backend/ltd/Cargo.toml'
	exit 0
fi

MODE=$1
[ -z "$MODE" ] && MODE=debug

BUILD=$2
[ -z "$BUILD" ] && BUILD=ltd


case ${UNAME_S} in
    Linux*)
	SO_DEFORMATION=target/$MODE/libdeformation.so
	SO_INTEGRATOR=target/$MODE/libintegrator.so
	SO_INTEGRAND=target/$MODE/libintegrand.so
	SO_LTD=target/$MODE/libltd.so;;
    Darwin*)
	SO_DEFORMATION=target/$MODE/libdeformation.dylib
	SO_INTEGRATOR=target/$MODE/libintegrator.dylib
	SO_INTEGRAND=target/$MODE/libintegrand.dylib
	SO_LTD=target/$MODE/libltd.dylib;;
    *)
	echo "UNKNOWN:${UNAME_S}"
	exit 0
esac

#Build libraries for python 
cd rust_backend/

if [ "$MODE" == debug ]; then
	cargo build -p $BUILD
else
	cargo build --release -p $BUILD
fi

#Rename them to be called from MadGraph
#cp ${SO_DEFORMATION} ../deformation.so
#cp ${SO_INTEGRAND} ../integrand.so
#cp ${SO_INTEGRATOR} ../integrator.so
cp ${SO_LTD} ../ltd.so

