graphs=[{'edges': {0: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p0',
                'name': 'p1',
                'vertices': [1, 8]},
            1: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p1',
                'name': 'p2',
                'vertices': [0, 9]},
            2: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p2',
                'name': 'p3',
                'vertices': [6, 3]},
            3: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'vertices': [7, 2]},
            4: {'PDG': 21,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0',
                'name': 'q1',
                'vertices': [4, 5]},
            5: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1',
                'name': 'q2',
                'vertices': [7, 4]},
            6: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0+k1',
                'name': 'q3',
                'vertices': [4, 8]},
            7: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1+p0+p1',
                'name': 'q4',
                'vertices': [5, 6]},
            8: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0+k1+p0+p1',
                'name': 'q5',
                'vertices': [9, 5]},
            9: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1+p0+p1-p2',
                'name': 'q6',
                'vertices': [6, 7]},
            10: {'PDG': 6,
                 'edge_type': 'virtual',
                 'indices': None,
                 'momentum': 'k0+k1+p0',
                 'name': 'q7',
                 'vertices': [8, 9]}},
  'nodes': {0: {'PDGs': [22],
                'edge_ids': [1],
                'indices': None,
                'momenta': ['p1'],
                'vertex_id': -1},
            1: {'PDGs': [22],
                'edge_ids': [0],
                'indices': None,
                'momenta': ['p0'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [3],
                'indices': None,
                'momenta': ['p0+p1-p2'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [2],
                'indices': None,
                'momenta': ['p2'],
                'vertex_id': -1},
            4: {'PDGs': [6, 6, 21],
                'edge_ids': [6, 5, 4],
                'indices': None,
                'momenta': ['k0+k1', 'k1', 'k0'],
                'vertex_id': 0},
            5: {'PDGs': [6, 6, 21],
                'edge_ids': [7, 8, 4],
                'indices': None,
                'momenta': ['k1+p0+p1', 'k0+k1+p0+p1', 'k0'],
                'vertex_id': 0},
            6: {'PDGs': [6, 6, 22],
                'edge_ids': [9, 7, 2],
                'indices': None,
                'momenta': ['k1+p0+p1-p2', 'k1+p0+p1', 'p2'],
                'vertex_id': 0},
            7: {'PDGs': [6, 6, 22],
                'edge_ids': [5, 9, 3],
                'indices': None,
                'momenta': ['k1', 'k1+p0+p1-p2', 'p0+p1-p2'],
                'vertex_id': 0},
            8: {'PDGs': [6, 6, 22],
                'edge_ids': [10, 6, 0],
                'indices': None,
                'momenta': ['k0+k1+p0', 'k0+k1', 'p0'],
                'vertex_id': 0},
            9: {'PDGs': [6, 6, 22],
                'edge_ids': [8, 10, 1],
                'indices': None,
                'momenta': ['k0+k1+p0+p1', 'k0+k1+p0', 'p1'],
                'vertex_id': 0}},
  'overal_factor': '-2'},
 {'edges': {0: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p0',
                'name': 'p1',
                'vertices': [1, 8]},
            1: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p1',
                'name': 'p2',
                'vertices': [0, 9]},
            2: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p2',
                'name': 'p3',
                'vertices': [6, 3]},
            3: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'vertices': [7, 2]},
            4: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0',
                'name': 'q1',
                'vertices': [5, 4]},
            5: {'PDG': 21,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0-k1-p0',
                'name': 'q2',
                'vertices': [4, 5]},
            6: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1+p0',
                'name': 'q3',
                'vertices': [4, 9]},
            7: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1+p0',
                'name': 'q4',
                'vertices': [8, 5]},
            8: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1+p2',
                'name': 'q5',
                'vertices': [7, 6]},
            9: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1',
                'name': 'q6',
                'vertices': [6, 8]},
            10: {'PDG': 6,
                 'edge_type': 'virtual',
                 'indices': None,
                 'momentum': 'k1+p0+p1',
                 'name': 'q7',
                 'vertices': [9, 7]}},
  'nodes': {0: {'PDGs': [22],
                'edge_ids': [1],
                'indices': None,
                'momenta': ['p1'],
                'vertex_id': -1},
            1: {'PDGs': [22],
                'edge_ids': [0],
                'indices': None,
                'momenta': ['p0'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [3],
                'indices': None,
                'momenta': ['p0+p1-p2'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [2],
                'indices': None,
                'momenta': ['p2'],
                'vertex_id': -1},
            4: {'PDGs': [6, 6, 21],
                'edge_ids': [6, 4, 5],
                'indices': None,
                'momenta': ['k1+p0', 'k0', 'k0-k1-p0'],
                'vertex_id': 0},
            5: {'PDGs': [6, 6, 21],
                'edge_ids': [4, 7, 5],
                'indices': None,
                'momenta': ['k0', 'k1+p0', 'k0-k1-p0'],
                'vertex_id': 0},
            6: {'PDGs': [6, 6, 22],
                'edge_ids': [9, 8, 2],
                'indices': None,
                'momenta': ['k1', 'k1+p2', 'p2'],
                'vertex_id': 0},
            7: {'PDGs': [6, 6, 22],
                'edge_ids': [8, 10, 3],
                'indices': None,
                'momenta': ['k1+p2', 'k1+p0+p1', 'p0+p1-p2'],
                'vertex_id': 0},
            8: {'PDGs': [6, 6, 22],
                'edge_ids': [7, 9, 0],
                'indices': None,
                'momenta': ['k1+p0', 'k1', 'p0'],
                'vertex_id': 0},
            9: {'PDGs': [6, 6, 22],
                'edge_ids': [10, 6, 1],
                'indices': None,
                'momenta': ['k1+p0+p1', 'k1+p0', 'p1'],
                'vertex_id': 0}},
  'overal_factor': '-4'},
 {'edges': {0: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p0',
                'name': 'p1',
                'vertices': [1, 8]},
            1: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p1',
                'name': 'p2',
                'vertices': [0, 9]},
            2: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p2',
                'name': 'p3',
                'vertices': [6, 3]},
            3: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'vertices': [7, 2]},
            4: {'PDG': 21,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0',
                'name': 'q1',
                'vertices': [4, 5]},
            5: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0+k1-p1',
                'name': 'q2',
                'vertices': [8, 4]},
            6: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1-p1',
                'name': 'q3',
                'vertices': [4, 9]},
            7: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1-p2',
                'name': 'q4',
                'vertices': [6, 5]},
            8: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0+k1-p2',
                'name': 'q5',
                'vertices': [5, 7]},
            9: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1',
                'name': 'q6',
                'vertices': [9, 6]},
            10: {'PDG': 6,
                 'edge_type': 'virtual',
                 'indices': None,
                 'momentum': 'k0+k1-p0-p1',
                 'name': 'q7',
                 'vertices': [7, 8]}},
  'nodes': {0: {'PDGs': [22],
                'edge_ids': [1],
                'indices': None,
                'momenta': ['p1'],
                'vertex_id': -1},
            1: {'PDGs': [22],
                'edge_ids': [0],
                'indices': None,
                'momenta': ['p0'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [3],
                'indices': None,
                'momenta': ['p0+p1-p2'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [2],
                'indices': None,
                'momenta': ['p2'],
                'vertex_id': -1},
            4: {'PDGs': [6, 6, 21],
                'edge_ids': [6, 5, 4],
                'indices': None,
                'momenta': ['k1-p1', 'k0+k1-p1', 'k0'],
                'vertex_id': 0},
            5: {'PDGs': [6, 6, 21],
                'edge_ids': [8, 7, 4],
                'indices': None,
                'momenta': ['k0+k1-p2', 'k1-p2', 'k0'],
                'vertex_id': 0},
            6: {'PDGs': [6, 6, 22],
                'edge_ids': [7, 9, 2],
                'indices': None,
                'momenta': ['k1-p2', 'k1', 'p2'],
                'vertex_id': 0},
            7: {'PDGs': [6, 6, 22],
                'edge_ids': [10, 8, 3],
                'indices': None,
                'momenta': ['k0+k1-p0-p1', 'k0+k1-p2', 'p0+p1-p2'],
                'vertex_id': 0},
            8: {'PDGs': [6, 6, 22],
                'edge_ids': [5, 10, 0],
                'indices': None,
                'momenta': ['k0+k1-p1', 'k0+k1-p0-p1', 'p0'],
                'vertex_id': 0},
            9: {'PDGs': [6, 6, 22],
                'edge_ids': [9, 6, 1],
                'indices': None,
                'momenta': ['k1', 'k1-p1', 'p1'],
                'vertex_id': 0}},
  'overal_factor': '-2'},
 {'edges': {0: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p0',
                'name': 'p1',
                'vertices': [1, 8]},
            1: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p1',
                'name': 'p2',
                'vertices': [0, 9]},
            2: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p2',
                'name': 'p3',
                'vertices': [6, 3]},
            3: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'vertices': [7, 2]},
            4: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0',
                'name': 'q1',
                'vertices': [5, 4]},
            5: {'PDG': 21,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1',
                'name': 'q2',
                'vertices': [4, 5]},
            6: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0-k1',
                'name': 'q3',
                'vertices': [4, 8]},
            7: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0-k1',
                'name': 'q4',
                'vertices': [7, 5]},
            8: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0-k1+p0+p1-p2',
                'name': 'q5',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0-k1+p0+p1',
                'name': 'q6',
                'vertices': [9, 6]},
            10: {'PDG': 6,
                 'edge_type': 'virtual',
                 'indices': None,
                 'momentum': 'k0-k1+p0',
                 'name': 'q7',
                 'vertices': [8, 9]}},
  'nodes': {0: {'PDGs': [22],
                'edge_ids': [1],
                'indices': None,
                'momenta': ['p1'],
                'vertex_id': -1},
            1: {'PDGs': [22],
                'edge_ids': [0],
                'indices': None,
                'momenta': ['p0'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [3],
                'indices': None,
                'momenta': ['p0+p1-p2'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [2],
                'indices': None,
                'momenta': ['p2'],
                'vertex_id': -1},
            4: {'PDGs': [6, 6, 21],
                'edge_ids': [6, 4, 5],
                'indices': None,
                'momenta': ['k0-k1', 'k0', 'k1'],
                'vertex_id': 0},
            5: {'PDGs': [6, 6, 21],
                'edge_ids': [4, 7, 5],
                'indices': None,
                'momenta': ['k0', 'k0-k1', 'k1'],
                'vertex_id': 0},
            6: {'PDGs': [6, 6, 22],
                'edge_ids': [8, 9, 2],
                'indices': None,
                'momenta': ['k0-k1+p0+p1-p2', 'k0-k1+p0+p1', 'p2'],
                'vertex_id': 0},
            7: {'PDGs': [6, 6, 22],
                'edge_ids': [7, 8, 3],
                'indices': None,
                'momenta': ['k0-k1', 'k0-k1+p0+p1-p2', 'p0+p1-p2'],
                'vertex_id': 0},
            8: {'PDGs': [6, 6, 22],
                'edge_ids': [10, 6, 0],
                'indices': None,
                'momenta': ['k0-k1+p0', 'k0-k1', 'p0'],
                'vertex_id': 0},
            9: {'PDGs': [6, 6, 22],
                'edge_ids': [9, 10, 1],
                'indices': None,
                'momenta': ['k0-k1+p0+p1', 'k0-k1+p0', 'p1'],
                'vertex_id': 0}},
  'overal_factor': '-4'},
 {'edges': {0: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p0',
                'name': 'p1',
                'vertices': [1, 8]},
            1: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p1',
                'name': 'p2',
                'vertices': [0, 9]},
            2: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p2',
                'name': 'p3',
                'vertices': [6, 3]},
            3: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'vertices': [7, 2]},
            4: {'PDG': 21,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0',
                'name': 'q1',
                'vertices': [4, 5]},
            5: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1+p0',
                'name': 'q2',
                'vertices': [8, 4]},
            6: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0+k1+p0',
                'name': 'q3',
                'vertices': [4, 9]},
            7: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1+p2',
                'name': 'q4',
                'vertices': [5, 6]},
            8: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0+k1+p2',
                'name': 'q5',
                'vertices': [7, 5]},
            9: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1',
                'name': 'q6',
                'vertices': [6, 8]},
            10: {'PDG': 6,
                 'edge_type': 'virtual',
                 'indices': None,
                 'momentum': 'k0+k1+p0+p1',
                 'name': 'q7',
                 'vertices': [9, 7]}},
  'nodes': {0: {'PDGs': [22],
                'edge_ids': [1],
                'indices': None,
                'momenta': ['p1'],
                'vertex_id': -1},
            1: {'PDGs': [22],
                'edge_ids': [0],
                'indices': None,
                'momenta': ['p0'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [3],
                'indices': None,
                'momenta': ['p0+p1-p2'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [2],
                'indices': None,
                'momenta': ['p2'],
                'vertex_id': -1},
            4: {'PDGs': [6, 6, 21],
                'edge_ids': [6, 5, 4],
                'indices': None,
                'momenta': ['k0+k1+p0', 'k1+p0', 'k0'],
                'vertex_id': 0},
            5: {'PDGs': [6, 6, 21],
                'edge_ids': [7, 8, 4],
                'indices': None,
                'momenta': ['k1+p2', 'k0+k1+p2', 'k0'],
                'vertex_id': 0},
            6: {'PDGs': [6, 6, 22],
                'edge_ids': [9, 7, 2],
                'indices': None,
                'momenta': ['k1', 'k1+p2', 'p2'],
                'vertex_id': 0},
            7: {'PDGs': [6, 6, 22],
                'edge_ids': [8, 10, 3],
                'indices': None,
                'momenta': ['k0+k1+p2', 'k0+k1+p0+p1', 'p0+p1-p2'],
                'vertex_id': 0},
            8: {'PDGs': [6, 6, 22],
                'edge_ids': [5, 9, 0],
                'indices': None,
                'momenta': ['k1+p0', 'k1', 'p0'],
                'vertex_id': 0},
            9: {'PDGs': [6, 6, 22],
                'edge_ids': [10, 6, 1],
                'indices': None,
                'momenta': ['k0+k1+p0+p1', 'k0+k1+p0', 'p1'],
                'vertex_id': 0}},
  'overal_factor': '-2'},
 {'edges': {0: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p0',
                'name': 'p1',
                'vertices': [1, 8]},
            1: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p1',
                'name': 'p2',
                'vertices': [0, 9]},
            2: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p2',
                'name': 'p3',
                'vertices': [6, 3]},
            3: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'vertices': [7, 2]},
            4: {'PDG': 21,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0',
                'name': 'q1',
                'vertices': [4, 5]},
            5: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0+k1+p0',
                'name': 'q2',
                'vertices': [8, 4]},
            6: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1+p0',
                'name': 'q3',
                'vertices': [4, 9]},
            7: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1',
                'name': 'q4',
                'vertices': [6, 5]},
            8: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0+k1',
                'name': 'q5',
                'vertices': [5, 8]},
            9: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1+p2',
                'name': 'q6',
                'vertices': [7, 6]},
            10: {'PDG': 6,
                 'edge_type': 'virtual',
                 'indices': None,
                 'momentum': 'k1+p0+p1',
                 'name': 'q7',
                 'vertices': [9, 7]}},
  'nodes': {0: {'PDGs': [22],
                'edge_ids': [1],
                'indices': None,
                'momenta': ['p1'],
                'vertex_id': -1},
            1: {'PDGs': [22],
                'edge_ids': [0],
                'indices': None,
                'momenta': ['p0'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [3],
                'indices': None,
                'momenta': ['p0+p1-p2'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [2],
                'indices': None,
                'momenta': ['p2'],
                'vertex_id': -1},
            4: {'PDGs': [6, 6, 21],
                'edge_ids': [6, 5, 4],
                'indices': None,
                'momenta': ['k1+p0', 'k0+k1+p0', 'k0'],
                'vertex_id': 0},
            5: {'PDGs': [6, 6, 21],
                'edge_ids': [8, 7, 4],
                'indices': None,
                'momenta': ['k0+k1', 'k1', 'k0'],
                'vertex_id': 0},
            6: {'PDGs': [6, 6, 22],
                'edge_ids': [7, 9, 2],
                'indices': None,
                'momenta': ['k1', 'k1+p2', 'p2'],
                'vertex_id': 0},
            7: {'PDGs': [6, 6, 22],
                'edge_ids': [9, 10, 3],
                'indices': None,
                'momenta': ['k1+p2', 'k1+p0+p1', 'p0+p1-p2'],
                'vertex_id': 0},
            8: {'PDGs': [6, 6, 22],
                'edge_ids': [5, 8, 0],
                'indices': None,
                'momenta': ['k0+k1+p0', 'k0+k1', 'p0'],
                'vertex_id': 0},
            9: {'PDGs': [6, 6, 22],
                'edge_ids': [10, 6, 1],
                'indices': None,
                'momenta': ['k1+p0+p1', 'k1+p0', 'p1'],
                'vertex_id': 0}},
  'overal_factor': '-6'},
 {'edges': {0: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p0',
                'name': 'p1',
                'vertices': [1, 8]},
            1: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p1',
                'name': 'p2',
                'vertices': [0, 9]},
            2: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p2',
                'name': 'p3',
                'vertices': [6, 3]},
            3: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'vertices': [7, 2]},
            4: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0',
                'name': 'q1',
                'vertices': [5, 4]},
            5: {'PDG': 21,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0-k1+p1',
                'name': 'q2',
                'vertices': [4, 5]},
            6: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1-p1',
                'name': 'q3',
                'vertices': [4, 9]},
            7: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1-p1',
                'name': 'q4',
                'vertices': [8, 5]},
            8: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1-p2',
                'name': 'q5',
                'vertices': [6, 7]},
            9: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1',
                'name': 'q6',
                'vertices': [9, 6]},
            10: {'PDG': 6,
                 'edge_type': 'virtual',
                 'indices': None,
                 'momentum': 'k1-p0-p1',
                 'name': 'q7',
                 'vertices': [7, 8]}},
  'nodes': {0: {'PDGs': [22],
                'edge_ids': [1],
                'indices': None,
                'momenta': ['p1'],
                'vertex_id': -1},
            1: {'PDGs': [22],
                'edge_ids': [0],
                'indices': None,
                'momenta': ['p0'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [3],
                'indices': None,
                'momenta': ['p0+p1-p2'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [2],
                'indices': None,
                'momenta': ['p2'],
                'vertex_id': -1},
            4: {'PDGs': [6, 6, 21],
                'edge_ids': [6, 4, 5],
                'indices': None,
                'momenta': ['k1-p1', 'k0', 'k0-k1+p1'],
                'vertex_id': 0},
            5: {'PDGs': [6, 6, 21],
                'edge_ids': [4, 7, 5],
                'indices': None,
                'momenta': ['k0', 'k1-p1', 'k0-k1+p1'],
                'vertex_id': 0},
            6: {'PDGs': [6, 6, 22],
                'edge_ids': [8, 9, 2],
                'indices': None,
                'momenta': ['k1-p2', 'k1', 'p2'],
                'vertex_id': 0},
            7: {'PDGs': [6, 6, 22],
                'edge_ids': [10, 8, 3],
                'indices': None,
                'momenta': ['k1-p0-p1', 'k1-p2', 'p0+p1-p2'],
                'vertex_id': 0},
            8: {'PDGs': [6, 6, 22],
                'edge_ids': [7, 10, 0],
                'indices': None,
                'momenta': ['k1-p1', 'k1-p0-p1', 'p0'],
                'vertex_id': 0},
            9: {'PDGs': [6, 6, 22],
                'edge_ids': [9, 6, 1],
                'indices': None,
                'momenta': ['k1', 'k1-p1', 'p1'],
                'vertex_id': 0}},
  'overal_factor': '-4'},
 {'edges': {0: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p0',
                'name': 'p1',
                'vertices': [1, 8]},
            1: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p1',
                'name': 'p2',
                'vertices': [0, 9]},
            2: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p2',
                'name': 'p3',
                'vertices': [6, 3]},
            3: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'vertices': [7, 2]},
            4: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0',
                'name': 'q1',
                'vertices': [5, 4]},
            5: {'PDG': 21,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1',
                'name': 'q2',
                'vertices': [4, 5]},
            6: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0-k1',
                'name': 'q3',
                'vertices': [4, 8]},
            7: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0-k1',
                'name': 'q4',
                'vertices': [6, 5]},
            8: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0-k1+p2',
                'name': 'q5',
                'vertices': [7, 6]},
            9: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0-k1+p0+p1',
                'name': 'q6',
                'vertices': [9, 7]},
            10: {'PDG': 6,
                 'edge_type': 'virtual',
                 'indices': None,
                 'momentum': 'k0-k1+p0',
                 'name': 'q7',
                 'vertices': [8, 9]}},
  'nodes': {0: {'PDGs': [22],
                'edge_ids': [1],
                'indices': None,
                'momenta': ['p1'],
                'vertex_id': -1},
            1: {'PDGs': [22],
                'edge_ids': [0],
                'indices': None,
                'momenta': ['p0'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [3],
                'indices': None,
                'momenta': ['p0+p1-p2'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [2],
                'indices': None,
                'momenta': ['p2'],
                'vertex_id': -1},
            4: {'PDGs': [6, 6, 21],
                'edge_ids': [6, 4, 5],
                'indices': None,
                'momenta': ['k0-k1', 'k0', 'k1'],
                'vertex_id': 0},
            5: {'PDGs': [6, 6, 21],
                'edge_ids': [4, 7, 5],
                'indices': None,
                'momenta': ['k0', 'k0-k1', 'k1'],
                'vertex_id': 0},
            6: {'PDGs': [6, 6, 22],
                'edge_ids': [7, 8, 2],
                'indices': None,
                'momenta': ['k0-k1', 'k0-k1+p2', 'p2'],
                'vertex_id': 0},
            7: {'PDGs': [6, 6, 22],
                'edge_ids': [8, 9, 3],
                'indices': None,
                'momenta': ['k0-k1+p2', 'k0-k1+p0+p1', 'p0+p1-p2'],
                'vertex_id': 0},
            8: {'PDGs': [6, 6, 22],
                'edge_ids': [10, 6, 0],
                'indices': None,
                'momenta': ['k0-k1+p0', 'k0-k1', 'p0'],
                'vertex_id': 0},
            9: {'PDGs': [6, 6, 22],
                'edge_ids': [9, 10, 1],
                'indices': None,
                'momenta': ['k0-k1+p0+p1', 'k0-k1+p0', 'p1'],
                'vertex_id': 0}},
  'overal_factor': '-4'},
 {'edges': {0: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p0',
                'name': 'p1',
                'vertices': [1, 8]},
            1: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p1',
                'name': 'p2',
                'vertices': [0, 9]},
            2: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p2',
                'name': 'p3',
                'vertices': [6, 3]},
            3: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'vertices': [7, 2]},
            4: {'PDG': 21,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0',
                'name': 'q1',
                'vertices': [4, 5]},
            5: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0+k1+p0',
                'name': 'q2',
                'vertices': [8, 4]},
            6: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1+p0',
                'name': 'q3',
                'vertices': [4, 9]},
            7: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1',
                'name': 'q4',
                'vertices': [7, 5]},
            8: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0+k1',
                'name': 'q5',
                'vertices': [5, 8]},
            9: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1+p0+p1-p2',
                'name': 'q6',
                'vertices': [6, 7]},
            10: {'PDG': 6,
                 'edge_type': 'virtual',
                 'indices': None,
                 'momentum': 'k1+p0+p1',
                 'name': 'q7',
                 'vertices': [9, 6]}},
  'nodes': {0: {'PDGs': [22],
                'edge_ids': [1],
                'indices': None,
                'momenta': ['p1'],
                'vertex_id': -1},
            1: {'PDGs': [22],
                'edge_ids': [0],
                'indices': None,
                'momenta': ['p0'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [3],
                'indices': None,
                'momenta': ['p0+p1-p2'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [2],
                'indices': None,
                'momenta': ['p2'],
                'vertex_id': -1},
            4: {'PDGs': [6, 6, 21],
                'edge_ids': [6, 5, 4],
                'indices': None,
                'momenta': ['k1+p0', 'k0+k1+p0', 'k0'],
                'vertex_id': 0},
            5: {'PDGs': [6, 6, 21],
                'edge_ids': [8, 7, 4],
                'indices': None,
                'momenta': ['k0+k1', 'k1', 'k0'],
                'vertex_id': 0},
            6: {'PDGs': [6, 6, 22],
                'edge_ids': [9, 10, 2],
                'indices': None,
                'momenta': ['k1+p0+p1-p2', 'k1+p0+p1', 'p2'],
                'vertex_id': 0},
            7: {'PDGs': [6, 6, 22],
                'edge_ids': [7, 9, 3],
                'indices': None,
                'momenta': ['k1', 'k1+p0+p1-p2', 'p0+p1-p2'],
                'vertex_id': 0},
            8: {'PDGs': [6, 6, 22],
                'edge_ids': [5, 8, 0],
                'indices': None,
                'momenta': ['k0+k1+p0', 'k0+k1', 'p0'],
                'vertex_id': 0},
            9: {'PDGs': [6, 6, 22],
                'edge_ids': [10, 6, 1],
                'indices': None,
                'momenta': ['k1+p0+p1', 'k1+p0', 'p1'],
                'vertex_id': 0}},
  'overal_factor': '-6'},
 {'edges': {0: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p0',
                'name': 'p1',
                'vertices': [1, 8]},
            1: {'PDG': 22,
                'edge_type': 'in',
                'indices': None,
                'momentum': 'p1',
                'name': 'p2',
                'vertices': [0, 9]},
            2: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p2',
                'name': 'p3',
                'vertices': [6, 3]},
            3: {'PDG': 22,
                'edge_type': 'out',
                'indices': None,
                'momentum': 'p0+p1-p2',
                'name': 'p4',
                'vertices': [7, 2]},
            4: {'PDG': 21,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0',
                'name': 'q1',
                'vertices': [4, 5]},
            5: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1',
                'name': 'q2',
                'vertices': [7, 4]},
            6: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0+k1',
                'name': 'q3',
                'vertices': [4, 9]},
            7: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1+p0+p1',
                'name': 'q4',
                'vertices': [5, 6]},
            8: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k0+k1+p0+p1',
                'name': 'q5',
                'vertices': [8, 5]},
            9: {'PDG': 6,
                'edge_type': 'virtual',
                'indices': None,
                'momentum': 'k1+p0+p1-p2',
                'name': 'q6',
                'vertices': [6, 7]},
            10: {'PDG': 6,
                 'edge_type': 'virtual',
                 'indices': None,
                 'momentum': 'k0+k1+p1',
                 'name': 'q7',
                 'vertices': [9, 8]}},
  'nodes': {0: {'PDGs': [22],
                'edge_ids': [1],
                'indices': None,
                'momenta': ['p1'],
                'vertex_id': -1},
            1: {'PDGs': [22],
                'edge_ids': [0],
                'indices': None,
                'momenta': ['p0'],
                'vertex_id': -1},
            2: {'PDGs': [22],
                'edge_ids': [3],
                'indices': None,
                'momenta': ['p0+p1-p2'],
                'vertex_id': -1},
            3: {'PDGs': [22],
                'edge_ids': [2],
                'indices': None,
                'momenta': ['p2'],
                'vertex_id': -1},
            4: {'PDGs': [6, 6, 21],
                'edge_ids': [6, 5, 4],
                'indices': None,
                'momenta': ['k0+k1', 'k1', 'k0'],
                'vertex_id': 0},
            5: {'PDGs': [6, 6, 21],
                'edge_ids': [7, 8, 4],
                'indices': None,
                'momenta': ['k1+p0+p1', 'k0+k1+p0+p1', 'k0'],
                'vertex_id': 0},
            6: {'PDGs': [6, 6, 22],
                'edge_ids': [9, 7, 2],
                'indices': None,
                'momenta': ['k1+p0+p1-p2', 'k1+p0+p1', 'p2'],
                'vertex_id': 0},
            7: {'PDGs': [6, 6, 22],
                'edge_ids': [5, 9, 3],
                'indices': None,
                'momenta': ['k1', 'k1+p0+p1-p2', 'p0+p1-p2'],
                'vertex_id': 0},
            8: {'PDGs': [6, 6, 22],
                'edge_ids': [8, 10, 0],
                'indices': None,
                'momenta': ['k0+k1+p0+p1', 'k0+k1+p1', 'p0'],
                'vertex_id': 0},
            9: {'PDGs': [6, 6, 22],
                'edge_ids': [10, 6, 1],
                'indices': None,
                'momenta': ['k0+k1+p1', 'k0+k1', 'p1'],
                'vertex_id': 0}},
  'overal_factor': '-2'}]