#!/usr/bin/env bash
./probe_hyperparameters.py \
	--t=Box \
	--Integrator.n_max=100000 \
	--Integrator.n_start=10000 \
	--Integrator.n_increase=0 \
	--save_results_to=hyperparameters_scan_test.dat \
	--Deformation.lambda=-1. \
	--Deformation.lambda_values=[-0.1*step for step in range\(1,11\)] \
	--Deformation.exponential.a_ij_values=[0.2*step for step in range\(1,11\)] \
	--correlated_variations=False \
#	--silence_rust
