#!/usr/bin/env sh
# --loop=100
./run_tests.py \
	--t=DoubleBox\
	--name=pole_check \
	--ps=[ \
		[19.6586,	-7.15252,	-0.206016,	8.96383],\
		[26.874,	 7.04203,	-0.0501295,-12.9055],\
		[43.4674,	 0.110491,	 0.256146,	3.9417],\
		[-90., 		 0.,		 0.,		0.] \
	] \
	--nh=100 \
	--s=[] \
	--d=[ \
	  [1.,1.,0.], \
	  [1.,1.,0.], \
	] \
	--p=[ \
      [1.2,1.3,1.4], \
	  [10.2,10.3,10.4], \
	] \
	--u=-1.0 \
	--v=-1.0 \
	--t_values_steps="linear" \
	--tr=[0.0,2.0] \
	--t_n_points=100 \
	--seed=1 \
	--analysis_options={\"log_x_scale\": False, \"log_y_scale\": False} \
    --save="test.yaml" \
	$1
