#!/usr/bin/env sh

./run_tests.py \
	--t=TriangleBox \
	--ps=[ \
		[39.7424,-14.1093, 0.102709, 20.4908], \
	    [50.2576, 14.1093,-0.102709,-20.4908], \
		[-90., 0.,0.,0.] \
	] \
	--nh=100 \
	--s=[] \
	--d=[ \
	  [0.3,0.4,-0.5], \
	  [-0.6,-0.7,0.8] \
	] \
	--u=0.2 \
	--v=0.7 \
	--tv="[10.**(-float(i)*0.1) for i in range(100)]" \
	--tr=[0.0,1.0] \
	--seed=1 \
	--analysis_options={\"log_x_scale\": True, \"log_y_scale\": True} \
    --save="test.yaml"
