#!/usr/bin/env sh
./run_tests.py \
	--t=Triangle\
	--ps=[ \
		[39.7424,-24.1093, -20.102709, 200.4908], \
	    [50.2576, 14.1093,-0.102709,-500.4908], \
		[-90., 10.,20.,300.] \
	] \
	--nh=1000 \
	--s=[] \
	--d=[ \
	  [0.3,0.4,-0.5], \
	] \
	--p=[ \
      [1.1,1.2,1.3,1.4], \
	] \
	--u=0.2 \
	--v=0.7 \
	--tv="[10.**(-float(i)*0.1) for i in range(100)]" \
	--tr=[0.0,1.0] \
	--seed=1 \
	--analysis_options={\"log_x_scale\": True, \"log_y_scale\": True} \
    --save="test.yaml"
