#!/usr/bin/env sh
# --loop=100
# --t=Decagon_P2_physical_massless \
# --t=Decagon_P1_one_ellipse_massless \
./run_tests.py \
	--t=Decagon_P1_one_ellipse_massless \
	--name=pole_check \
	--nh=100 \
	--s=[] \
	--t_values_steps="linear" \
	--tr=[0.0,0.99] \
	--u=0.001 \
    --v=0.001 \
	--d=[[1.0,1.0,1.0],[1.0,1.0,1.0]] \
	--tr=[0.0,1.0] \
	--t_n_points=100 \
	--seed=1 \
	--analysis_options={\"log_x_scale\": False, \"log_y_scale\": False, \"n_points_to_show\":100} \
    --save="test.yaml" \
	$1
