#!/usr/bin/env sh
# --loop=100
./run_tests.py \
	--t=Decagon_P2_physical_massless\
	--name=pole_check \
	--nh=100 \
	--s=[] \
	--t_values_steps="linear" \
	--tr=[0.0,2.0] \
	--u=-1.0 \
    --v=-1.0 \
	--d=[[1.0,1.0,1.0],[1.0,1.0,1.0]] \
	--tr=[0.1,0.8] \
	--t_n_points=100 \
	--seed=1 \
	--analysis_options={\"log_x_scale\": False, \"log_y_scale\": False} \
    --save="test.yaml" \
	$1
